# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boocarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpart',
            old_name='purchaser',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='carpart',
            name='note',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
