# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boocarapp', '0002_auto_20170624_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='amount',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
